name: Autotools

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install prereq
      run: sudo apt-get install libtool libtool-bin
    - uses: actions/checkout@v3
    - name: buildconf
      run: ./buildconf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
