name: Autotools

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  MARGS: "-j2"

jobs:

  build:
    strategy:
      matrix:
        include: 
          - name: Default
          - name: Static
            config: --enable-static
          - name: Maintainer-mode
            config: --enable-maintainer-mode
          - name: Pool-debug
            config: --enable-pool-debug
          - name: Pool-debug, maintainer-mode
            config: --enable-pool-debug --enable-maintainer-mode
          - name: Maintainer-mode, no IPv6
            config: --enable-maintainer-mode --disable-ipv6
          - name: Maintainer-mode, -Werror
            notest-cflags: -Werror
            config: --enable-maintainer-mode
       
    runs-on: ubuntu-latest
    env:
      NOTEST_CFLAGS: ${{matrix.notest-cflags}
      
    steps:
    - name: Install prereq
      run: sudo apt-get install libtool libtool-bin
    - uses: actions/checkout@v3
    - name: buildconf
      run: ./buildconf
    - name: configure
      run: ./configure ${{ matrix.config }}
    - name: make
      run: make $MARGS
    - name: make check
      run: make check
